In [1]:
import pandas as pd 
import numpy as np

In [2]:
df = pd.read_csv("../Data/DataCoSupplyChainDataset.csv", encoding="latin1")

In [3]:
'''Data Understanding & Data Quality Check'''

'Data Understanding & Data Quality Check'

In [4]:
'''Structure & Dimension Check'''
print("Shape data:", df.shape)
df.info

display(df.head())
display(df.tail())
display(df.sample(5))

Shape data: (180519, 53)

,Type,Days for shipping (real),Days for shipment (scheduled),Benefit per order,Sales per customer,Delivery Status,Late_delivery_risk,Category Id,Category Name,Customer City,...,Order Zipcode,Product Card Id,Product Category Id,Product Description,Product Image,Product Name,Product Price,Product Status,shipping date (DateOrders),Shipping Mode
0,DEBIT,3,4,91.250000,314.640015,Advance shipping,0,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,2/3/2018 22:56,Standard Class
1,TRANSFER,5,4,-249.089996,311.359985,Late delivery,1,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/18/2018 12:27,Standard Class
2,CASH,4,4,-247.779999,309.720001,Shipping on time,0,73,Sporting Goods,San Jose,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/17/2018 12:06,Standard Class
3,DEBIT,3,4,22.860001,304.809998,Advance shipping,0,73,Sporting Goods,Los Angeles,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/16/2018 11:45,Standard Class
4,PAYMENT,2,4,134.210007,298.250000,Advance shipping,0,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/15/2018 11:24,Standard Class

,Type,Days for shipping (real),Days for shipment (scheduled),Benefit per order,Sales per customer,Delivery Status,Late_delivery_risk,Category Id,Category Name,Customer City,...,Order Zipcode,Product Card Id,Product Category Id,Product Description,Product Image,Product Name,Product Price,Product Status,shipping date (DateOrders),Shipping Mode
180514,CASH,4,4,40.000000,399.980011,Shipping on time,0,45,Fishing,Brooklyn,...,NaN,1004,45,NaN,http://images.acmesports.sports/Field+%26+Stre...,Field & Stream Sportsman 16 Gun Fire Safe,399.980011,0,1/20/2016 3:40,Standard Class
180515,DEBIT,3,2,-613.770019,395.980011,Late delivery,1,45,Fishing,Bakersfield,...,NaN,1004,45,NaN,http://images.acmesports.sports/Field+%26+Stre...,Field & Stream Sportsman 16 Gun Fire Safe,399.980011,0,1/19/2016 1:34,Second Class
180516,TRANSFER,5,4,141.110001,391.980011,Late delivery,1,45,Fishing,Bristol,...,NaN,1004,45,NaN,http://images.acmesports.sports/Field+%26+Stre...,Field & Stream Sportsman 16 Gun Fire Safe,399.980011,0,1/20/2016 21:00,Standard Class
180517,PAYMENT,3,4,186.229996,387.980011,Advance shipping,0,45,Fishing,Caguas,...,NaN,1004,45,NaN,http://images.acmesports.sports/Field+%26+Stre...,Field & Stream Sportsman 16 Gun Fire Safe,399.980011,0,1/18/2016 20:18,Standard Class
180518,PAYMENT,4,4,168.949997,383.980011,Shipping on time,0,45,Fishing,Caguas,...,NaN,1004,45,NaN,http://images.acmesports.sports/Field+%26+Stre...,Field & Stream Sportsman 16 Gun Fire Safe,399.980011,0,1/19/2016 18:54,Standard Class

,Type,Days for shipping (real),Days for shipment (scheduled),Benefit per order,Sales per customer,Delivery Status,Late_delivery_risk,Category Id,Category Name,Customer City,...,Order Zipcode,Product Card Id,Product Category Id,Product Description,Product Image,Product Name,Product Price,Product Status,shipping date (DateOrders),Shipping Mode
43935,DEBIT,0,0,46.740002,245.979996,Shipping on time,0,43,Camping & Hiking,Irving,...,NaN,957,43,NaN,http://images.acmesports.sports/Diamondback+Wo...,Diamondback Women's Serene Classic Comfort Bi,299.980011,0,8/29/2016 16:45,Same Day
74178,DEBIT,4,2,80.639999,167.990005,Late delivery,1,48,Water Sports,Caguas,...,NaN,1073,48,NaN,http://images.acmesports.sports/Pelican+Sunstr...,Pelican Sunstream 100 Kayak,199.990005,0,10/18/2016 16:36,Second Class
180078,DEBIT,6,4,124.489998,331.980011,Late delivery,1,45,Fishing,Milpitas,...,NaN,1004,45,NaN,http://images.acmesports.sports/Field+%26+Stre...,Field & Stream Sportsman 16 Gun Fire Safe,399.980011,0,2/15/2016 18:42,Standard Class
131015,DEBIT,3,4,41.560001,125.949997,Advance shipping,0,46,Indoor/Outdoor Games,Tampa,...,NaN,1014,46,NaN,http://images.acmesports.sports/O%27Brien+Men%...,O'Brien Men's Neoprene Life Vest,49.980000,0,3/31/2016 16:32,Standard Class
70908,TRANSFER,2,1,28.219999,80.620003,Late delivery,1,37,Electronics,Levittown,...,NaN,822,37,NaN,http://images.acmesports.sports/Titleist+Pro+V...,Titleist Pro V1x High Numbers Golf Balls,47.990002,0,9/20/2016 20:08,First Class

In [5]:
df.columns

Index(['Type', 'Days for shipping (real)', 'Days for shipment (scheduled)',
       'Benefit per order', 'Sales per customer', 'Delivery Status',
       'Late_delivery_risk', 'Category Id', 'Category Name', 'Customer City',
       'Customer Country', 'Customer Email', 'Customer Fname', 'Customer Id',
       'Customer Lname', 'Customer Password', 'Customer Segment',
       'Customer State', 'Customer Street', 'Customer Zipcode',
       'Department Id', 'Department Name', 'Latitude', 'Longitude', 'Market',
       'Order City', 'Order Country', 'Order Customer Id',
       'order date (DateOrders)', 'Order Id', 'Order Item Cardprod Id',
       'Order Item Discount', 'Order Item Discount Rate', 'Order Item Id',
       'Order Item Product Price', 'Order Item Profit Ratio',
       'Order Item Quantity', 'Sales', 'Order Item Total',
       'Order Profit Per Order', 'Order Region', 'Order State', 'Order Status',
       'Order Zipcode', 'Product Card Id', 'Product Category Id',
       'Product Description', 'Product Image', 'Product Name', 'Product Price',
       'Product Status', 'shipping date (DateOrders)', 'Shipping Mode'],
      dtype='str')

In [6]:
# Check missing value explicit
missing_data = pd.DataFrame({
    'total_missing' : df.isnull().sum(),
    'percentage_of_missing' : (df.isnull().sum() / len(df)) * 100
})
missing_data[missing_data['total_missing'] > 0 ]

                     total_missing  percentage_of_missing
Customer Lname                   8               0.004432
Customer Zipcode                 3               0.001662
Order Zipcode               155679              86.239676
Product Description         180519             100.000000

In [7]:
# Check missing value implicit
implicit_missing = ['?', '-', 'N/A', 'null', 'none', ' ']
for col in df.select_dtypes(include=['object', 'string']).columns:
    found = df[col].astype(str).str.strip().isin(implicit_missing).sum()
    if found > 0:
        print(f"column'{col}' has {found} missing value")
print("done")

done

In [8]:
#Duplicated row
print("Total duplicated rows :", df.duplicated().sum())

#unique id
print("total unique order id :", df['Order Id'].nunique())
print("total unique order item id :", df['Order Item Id'].nunique())

Total duplicated rows : 0
total unique order id : 65752
total unique order item id : 180519

In [9]:
#Categorical data check 
for col in df.select_dtypes(include=['object', 'category', 'string']).columns:
    print(f"colums: '{col}' (unique: '{df[col].nunique()}')")
    print(df[col].value_counts(dropna=False).head(10))
    print("-" * 40)

colums: 'Type' (unique: '4')
Type
DEBIT       69295
TRANSFER    49883
PAYMENT     41725
CASH        19616
Name: count, dtype: int64
----------------------------------------
colums: 'Delivery Status' (unique: '4')
Delivery Status
Late delivery        98977
Advance shipping     41592
Shipping on time     32196
Shipping canceled     7754
Name: count, dtype: int64
----------------------------------------
colums: 'Category Name' (unique: '50')
Category Name
Cleats                  24551
Men's Footwear          22246
Women's Apparel         21035
Indoor/Outdoor Games    19298
Fishing                 17325
Water Sports            15540
Camping & Hiking        13729
Cardio Equipment        12487
Shop By Sport           10984
Electronics              3156
Name: count, dtype: int64
----------------------------------------
colums: 'Customer City' (unique: '563')
Customer City
Caguas          66770
Chicago          3885
Los Angeles      3417
Brooklyn         3412
New York         1816
Philadelphia     1577
Bronx            1500
San Diego        1437
Miami            1314
Houston          1297
Name: count, dtype: int64
----------------------------------------
colums: 'Customer Country' (unique: '2')
Customer Country
EE. UU.        111146
Puerto Rico     69373
Name: count, dtype: int64
----------------------------------------
colums: 'Customer Email' (unique: '1')
Customer Email
XXXXXXXXX    180519
Name: count, dtype: int64
----------------------------------------
colums: 'Customer Fname' (unique: '782')
Customer Fname
Mary        65150
James        1835
Robert       1759
Michael      1680
David        1625
John         1446
William      1365
Joseph       1117
Jennifer     1033
Richard      1032
Name: count, dtype: int64
----------------------------------------
colums: 'Customer Lname' (unique: '1109')
Customer Lname
Smith       64104
Johnson       989
Brown         909
Williams      869
Jones         859
Garcia        724
Wilson        675
Taylor        661
Davis         640
Moore         599
Name: count, dtype: int64
----------------------------------------
colums: 'Customer Password' (unique: '1')
Customer Password
XXXXXXXXX    180519
Name: count, dtype: int64
----------------------------------------
colums: 'Customer Segment' (unique: '3')
Customer Segment
Consumer       93504
Corporate      54789
Home Office    32226
Name: count, dtype: int64
----------------------------------------
colums: 'Customer State' (unique: '46')
Customer State
PR    69373
CA    29223
NY    11327
TX     9103
IL     7631
FL     5456
OH     4095
PA     3824
MI     3804
NJ     3191
Name: count, dtype: int64
----------------------------------------
colums: 'Customer Street' (unique: '7458')
Customer Street
9126 Wishing Expressway       122
4388 Burning Goose Ridge      117
4720 Noble Hills Wynd         116
2878 Hazy Wagon  Thicket      113
398 Emerald Grove             109
3593 Blue Brook Acres         108
2210 Merry Leaf Row           107
6289 Rocky Way                107
2585 Silent Autumn Landing    105
7694 Velvet Turnabout         103
Name: count, dtype: int64
----------------------------------------
colums: 'Department Name' (unique: '11')
Department Name
Fan Shop      66861
Apparel       48998
Golf          33220
Footwear      14525
Outdoors       9686
Fitness        2479
Discs Shop     2026
Technology     1465
Pet Shop        492
Book Shop       405
Name: count, dtype: int64
----------------------------------------
colums: 'Market' (unique: '5')
Market
LATAM           51594
Europe          50252
Pacific Asia    41260
USCA            25799
Africa          11614
Name: count, dtype: int64
----------------------------------------
colums: 'Order City' (unique: '3597')
Order City
Santo Domingo    2211
New York City    2202
Los Angeles      1845
Tegucigalpa      1783
Managua          1682
Mexico City      1484
Manila           1381
Philadelphia     1302
San Francisco    1297
London           1187
Name: count, dtype: int64
----------------------------------------
colums: 'Order Country' (unique: '164')
Order Country
Estados Unidos    24840
Francia           13222
México            13172
Alemania           9564
Australia          8497
Brasil             7987
Reino Unido        7302
China              5758
Italia             4989
India              4783
Name: count, dtype: int64
----------------------------------------
colums: 'order date (DateOrders)' (unique: '65752')
order date (DateOrders)
10/25/2016 14:39    5
3/30/2016 4:37      5
11/28/2016 1:18     5
9/8/2015 12:15      5
8/4/2017 2:31       5
7/2/2015 19:42      5
3/28/2015 0:55      5
4/10/2015 0:02      5
4/11/2017 15:49     5
3/29/2015 10:33     5
Name: count, dtype: int64
----------------------------------------
colums: 'Order Region' (unique: '23')
Order Region
Central America    28341
Western Europe     27109
South America      14935
Oceania            10148
Northern Europe     9792
Southeast Asia      9539
Southern Europe     9431
Caribbean           8318
West of USA         7993
South Asia          7731
Name: count, dtype: int64
----------------------------------------
colums: 'Order State' (unique: '1089')
Order State
Inglaterra                     6722
California                     4966
Isla de Francia                4580
Renania del Norte-Westfalia    3303
San Salvador                   3055
Nueva York                     2753
Distrito Federal               2559
Texas                          2446
Nueva Gales del Sur            2370
Santo Domingo                  2211
Name: count, dtype: int64
----------------------------------------
colums: 'Order Status' (unique: '9')
Order Status
COMPLETE           59491
PENDING_PAYMENT    39832
PROCESSING         21902
PENDING            20227
CLOSED             19616
ON_HOLD             9804
SUSPECTED_FRAUD     4062
CANCELED            3692
PAYMENT_REVIEW      1893
Name: count, dtype: int64
----------------------------------------
colums: 'Product Image' (unique: '118')
Product Image
http://images.acmesports.sports/Perfect+Fitness+Perfect+Rip+Deck                          24515
http://images.acmesports.sports/Nike+Men%27s+CJ+Elite+2+TD+Football+Cleat                 22246
http://images.acmesports.sports/Nike+Men%27s+Dri-FIT+Victory+Golf+Polo                    21035
http://images.acmesports.sports/O%27Brien+Men%27s+Neoprene+Life+Vest                      19298
http://images.acmesports.sports/Field+%26+Stream+Sportsman+16+Gun+Fire+Safe               17325
http://images.acmesports.sports/Pelican+Sunstream+100+Kayak                               15500
http://images.acmesports.sports/Diamondback+Women%27s+Serene+Classic+Comfort+Bike+2014    13729
http://images.acmesports.sports/Nike+Men%27s+Free+5.0%2B+Running+Shoe                     12169
http://images.acmesports.sports/Under+Armour+Girls%27+Toddler+Spine+Surge+Running+Shoe    10617
http://images.acmesports.sports/Fighting+video+games                                        838
Name: count, dtype: int64
----------------------------------------
colums: 'Product Name' (unique: '118')
Product Name
Perfect Fitness Perfect Rip Deck                 24515
Nike Men's CJ Elite 2 TD Football Cleat          22246
Nike Men's Dri-FIT Victory Golf Polo             21035
O'Brien Men's Neoprene Life Vest                 19298
Field & Stream Sportsman 16 Gun Fire Safe        17325
Pelican Sunstream 100 Kayak                      15500
Diamondback Women's Serene Classic Comfort Bi    13729
Nike Men's Free 5.0+ Running Shoe                12169
Under Armour Girls' Toddler Spine Surge Runni    10617
Fighting video games                               838
Name: count, dtype: int64
----------------------------------------
colums: 'shipping date (DateOrders)' (unique: '63701')
shipping date (DateOrders)
5/9/2015 18:02      10
9/27/2015 20:28     10
9/24/2015 23:48     10
8/1/2015 18:37      10
11/15/2016 13:45    10
2/26/2017 23:36     10
4/14/2017 4:26      10
2/1/2015 2:35       10
6/23/2017 4:20      10
6/5/2017 12:25      10
Name: count, dtype: int64
----------------------------------------
colums: 'Shipping Mode' (unique: '4')
Shipping Mode
Standard Class    107752
Second Class       35216
First Class        27814
Same Day            9737
Name: count, dtype: int64
----------------------------------------

In [10]:
# Descriptive statistics for numerical columns
df.describe().T

# Detection of illogical values

num_cols = df.select_dtypes(include='number').columns
for col in num_cols:
    negatives = (df[col] < 0).sum()
    if negatives > 0:
        print(f"Column'{col}' has {negatives} negative value")

Column'Benefit per order' has 33784 negative value
Column'Latitude' has 9 negative value
Column'Longitude' has 180414 negative value
Column'Order Item Profit Ratio' has 33784 negative value
Column'Order Profit Per Order' has 33784 negative value

In [11]:
# Conclution

'''



'''

'\n\n\n\n'

In [ ]:
df = df.rename(columns={
                'Type': 'type',
                'Days for shipping (real)': 'days_for_shipping',
                'Days for shipment (scheduled)': 'days_for_shipment',
                'Benefit per order': 'benefit_per_order',
                'Sales per customer': 'sales_per_customer',
                'Delivery Status': 'delivery_status',
                'Late_delivery_risk': 'late_delivery_risk', 
                'Category Id': 'category_id',
                'Category Name': 'category_name',
                'Customer City': 'customer_city',
                'Customer Country': 'customer_country',
                'Customer Email': 'customer_email',
                'Customer Fname': 'customer_fname',
                'Customer Id': 'Customer_id',
                'Customer Lname': 'customer_lname',
                'Customer Password': 'customer_password',
                'Customer Segment': 'customer_segment',
                'Customer State': 'customer_state',
                'Customer Street': 'customer_street',
                'Customer Zipcode': 'customer+zipcode',
                'Department Id': 'department_id',
                'Department Name': 'department_name',
                'Latitude': 'latitude',
                'Longitude': 'longtitude',
                'Market': 'market',
                'Order City': 'order_city',
                'Order Country': 'order_country',
                'Order Customer Id': 'order_customer_id',
                'order date (DateOrders)': 'order_date',
                'Order Id': 'order_id',
                'Order Item Cardprod Id': 'order_item_cardprod_id',
                'Order Item Discount': 'order_item_discount',
                'Order Item Discount Rate': 'oder_item_discount_rate',
                'Order Item Id': 'order_item_id',
                'Order Item Product Price': 'order_item_product_price',
                'Order Item Profit Ratio': 'order_item_profit_ratio',
                'Order Item Quantity': 'order_item_quantity',
                'Sales': 'sales',
                'Order Item Total': 'order_item_total',
                'Order Profit Per Order': 'order_profit_per_order',
                'Order Region': 'order_region',
                'Order State': 'order_state',
                'Order Status': 'order_status',
                'Order Zipcode': 'order_zipcode',
                'Product Card Id': 'product_card_id',
                'Product Category Id': 'product_category_id',
                'Product Description': 'product_description',
                'Product Image': 'product_image',
                'Product Name': 'product_name',
                'Product Price': 'product_price',
                'Product Status': 'product_status',
                'shipping date (DateOrders)': 'shipping_date',
                'Shipping Mode': 'shipping_mode'
})

In [13]:
df.columns

Index(['type', 'days_for_shipping', 'days_for_shipment', 'benefit_per_order',
       'sales_per_customer', 'delivery_status', 'late_delivery_risk',
       'category_id', 'category_name', 'customer_city', 'customer_country',
       'customer_email', 'customer_fname', 'Customer_id', 'customer_lname',
       'customer_password', 'customer_segment', 'customer_state',
       'customer_street', 'customer+zipcode', 'department_id',
       'department_name', 'latitude', 'longtitude', 'market', 'order_city',
       'order_country', 'order_customer_id', 'order_date', 'order_id',
       'order_item_cardprod_id', 'order_item_discount',
       'oder_item_discount_rate', 'order_item_id', 'order_item_product_price',
       'order_item_profit_ratio', 'order_item_quantity', 'sales',
       'order_item_total', 'order_profit_per_order', 'order_region',
       'order_state', 'order_status', 'order_zipcode', 'product_card_id',
       'product_category_id', 'product_description', 'product_image',
       'product_name', 'product_price', 'product_status', 'shipping_date',
       'shipping_mode'],
      dtype='str')

In [14]:
# Load into sql 

from sqlalchemy import create_engine

engine = create_engine(
    "postgresql+psycopg2://postgres:123456@localhost:5432/suplay_chain"
)

df.to_sql(
    'suplays',
    engine,
    if_exists='replace',
    index=False
)

31